apiVersion: v1
kind: ConfigMap
metadata:
  name: aline-config
data:
  DB_HOST: cc-aline-project-eks-database.cpadrttjochn.us-east-2.rds.amazonaws.com
  DB_PORT: '3306'
  DB_NAME: aline
#  UNDERWRITER_PORT: '8170'
#  USER_PORT: '8177'
#  TRANSACTION_PORT: '8178'
#  BANK_PORT: '8172'
#  CARD_PORT: '8174'
#  ACCOUNT_PORT: '8176'